### ISSUE TITLE
[CLI] webp and avif is not running on gitlab ci

### ISSUE THREAD

**Issue by sprabowo** [GoogleChromeLabs/squoosh#909]
**Describe the bug**
when script's running squoosh-cli in gitlab. it won't execute webp and avif.

**To Reproduce**
1. running script: `npm i -g @squoosh/cli && squoosh-cli ./public/images/homebanner.jpg --webp --avif  -d ./build/images/`
2. See squoosh-cli log result

**Expected behavior**
it should generate webp and avif like in figure 2

**Version:**
 - CLI squoosh version: 0.6.0
 - Node version: 10.20
 - npm version: 6.14.8

**Issue related to generate avif and webp on gitlab ci**

![image](https://user-images.githubusercontent.com/11748183/101999554-dd823080-3d10-11eb-8b2d-443f2b943499.png)
(figure 1. gitlab ci log)

**Additional context, screenshots, screencasts**

if i run webp, avif in Github Action. it works well
![image](https://user-images.githubusercontent.com/11748183/101999598-423d8b00-3d11-11eb-9ace-5686d10407be.png)
(figure 2. github action log)

**Comment by surma** [comment]
You need to pass individual images to the CLI, not a folder. So changing this to
```
npm i -g @squoosh/cli && squoosh-cli ./public/images/homebanner.jpg --webp --avif -d ./build/images/*
```

should fix it.

Please re-open if it doesn’t, tho :)

**Comment by surma** [comment]
(I misread what you had written. I have deleted my comment)

**Comment by surma** [comment]
Can you do me a favor and try running it with `--webp '{}' --avif '{}'` and see if that fixes it?

**Comment by sprabowo** [comment]
Thanks for your response @surma,
I've tried your tricks but it still doesn't work for gitlab. here i attach my insight:

run on gitlab [still **doesn't work**]
![image](https://user-images.githubusercontent.com/11748183/102024269-a587f580-3dc3-11eb-8a0c-e3dff73dfdc1.png)

run on github action [**work**]
![image](https://user-images.githubusercontent.com/11748183/102024290-bf293d00-3dc3-11eb-9699-3b98dc24f6b3.png)

run on travis-ci [**work**]
![image](https://user-images.githubusercontent.com/11748183/102024308-dff19280-3dc3-11eb-8fe0-974a02bd7c7c.png)

i run it on local machine and it works but i don't love to :( so i try to build in pipeline

**Comment by surma** [comment]
Weiiiird. What version of Node is running on gitlab CI?

**Comment by sprabowo** [comment]
i used image node/12.20.0 on gitlab-ci.yml. Before i was trying node/latest, node/alpine but still the same result. It couldn't generate webp and avif.

**Comment by surma** [comment]
I can't really help you debug gitlab, tho :( Maybe it's worth running your CI in a docker container?

**Comment by sprabowo** [comment]
No probs. thanks for response again. maybe i'll close this issue. will come back if there's any issue. 

i've just tested in multiple CI provider to ensure it works everywhere. for my project i'd choose provider that compatible only
