### ISSUE TITLE
[CLI] Unsupported format error: Not stopped CLI

### ISSUE THREAD

**Issue by nape-max** [GoogleChromeLabs/squoosh#983]
![image](https://user-images.githubusercontent.com/61621369/113147824-dc323080-9239-11eb-9679-9e4d08ba2e37.png)

**Describe the bug**
I tried to use this CLI for convert few JPG images to AVIF. When this find Image that maybe broken, he shows error and continue infinity 'Decode' operation that never stopped.

1. Find any file (txt, or archive e t.c.)
2. Rename it to *your_name*.jpg
3. Run `squoosh-cli *your_name*.jpg --avif
4. See error and not stopped CLI.

Expected behavior:
Stop script after error (if no more images) or continue convert other in list.

Version:
 - OS: Ubuntu 20.04
 - Node version: v14.16.0
 - npm version: 6.14.11

Original image: 
![1](https://user-images.githubusercontent.com/61621369/113147887-ec4a1000-9239-11eb-984d-f0165f6b60d6.jpg)

Output image: Nothing.

**Comment by atjn** [comment]
This is a pretty big issue for my use case, because squoosh is part of a larger automated workflow which has proper error handling if a file conversion fails, but now it just doesn't work because it thinks the process is still going.

**Comment by surma** [comment]
I just published `@squoosh/cli` v0.7.1 which should fix this! Can you give it another try?

I’ll close this bug, but please re-open if it’s still breaking for you!

**Comment by atjn** [comment]
I just tried to re-run `@squoosh/cli` v0.7.1 on a folder with known bad images, and it still breaks and hangs as described above. Let me know if you need more details.

**Comment by jcao219** [comment]
I'm only 50% sure, as I've only tested with the supplied image, but I think my PR #1075 may fix this hanging issue.

**Comment by atjn** [comment]
@jcao219 I just tested your PR, and I would say it fixes this problem. It still isn't optimal; it can take tens of seconds for the process to terminate after an error occurred, and there are still edge cases where the encoders themselves hang, but the main issue is fixed IMO.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
